# Generated by Django 3.2.5 on 2022-03-31 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='parent',
        ),
    ]
